### ISSUE TITLE
No new blocks after 829,999

### ISSUE THREAD

**Issue by clockuniverse** [clockuniverse/terracoin#6]
Getting error getblocktemplate call failed for daemon instance 0 with error {"code":-1,"message":"CreateNewBlock: TestBlockValidity failed: late-legacy-block (code 16)"}

**Comment by clockuniverse** [comment]
Another person has the same thing:  2016-09-22 05:34:36 ERROR: ContextualCheckBlockHeader : legacy block after auxpow start
2016-09-22 05:34:36 ERROR: TestBlockValidity: Consensus::ContextualCheckBlockHeader: late-legacy-block (code 16)

**Comment by crackfoo** [comment]
Same on my pool as well.

**Comment by ahmedbodi** [comment]
That means theyre not doing aux mining

**Comment by clockuniverse** [comment]
There is more to it then that.  Look at the bitcointalk thread people are saying that they know how to merge mine and it isn't working.  Also, we have multiple mining sites running the new wallet and I imagine they know what they are doing.

**Comment by crackfoo** [comment]
yeah I don't get it... I have a lot of coins and merge mining with 6 of them...

**Comment by crackfoo** [comment]
terracoin-cli getauxblock
error code: -1
error message:
CreateNewBlock: TestBlockValidity failed: late-legacy-block (code 16)

**Comment by hanzac** [comment]
Can @ahmedbodi explain why this code is written like this?

https://github.com/clockuniverse/terracoin/blob/master/src/primitives/pureheader.h
`
    inline bool IsLegacy() const
    {
	return nVersion <= 536870912;
}
`
536870912 is 2[sup]29[/sup], this is very strange, it seems no where to set big value like this.


While the dogecoin is written like this.
https://github.com/dogecoin/dogecoin/blob/master/src/primitives/pureheader.h
`
    inline bool IsLegacy() const
    {
        return nVersion == 1
            || (nVersion == 2 && GetChainId() == 0);
    }
`

**Comment by hrobeers** [comment]
I've been contacted by craslovell on the peercoin forum to take a look at this.
I believe @hanzac found the issue here, however I'd need to investigate it deeper to be sure.
Putting such a high version number in the header makes no sense.

**Why didn't you guys test this on a testnet first?**
Doing protocol changes without testing them will kill your coin.

**Comment by ahmedbodi** [comment]
It was written like that because terrcoin has blocks with that version number which are not aux blocks

**Comment by ahmedbodi** [comment]
And terracoin does not have a working testnet and you need a mining pool to do aux mining which none of the team have and is not a simple task to setup (dont forget i didnt ask for much in terms of payment to get this done)

**Comment by ahmedbodi** [comment]
Ok. Can you guys enable legacy mining in chainparams then recompile and mine. See if that fixes it

**Comment by clockuniverse** [comment]
So from what I understand this the commits Ahmed did earlier today should cover the issue.  So I am going to close this issue tomorrow (Just in case).

Thanks for the help everyone!!

@hrobeers Every step forward is a lesson learned.  I will make sure we have a working testnet before making changes going forward.  I also am going to have a TRC Foundation run p2pool to test things eventually.  Thanks!
